In [5]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [10]:
df = pd.read_excel('/Users/ishanthakkar/Desktop/Customer_Segmentation/data/raw/Online_Retail.xlsx')

In [9]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [12]:
df.shape

(541909, 8)

In [13]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [14]:
df = df.dropna(subset=['CustomerID'])

In [15]:
df = df.drop(columns=['Description'])

In [16]:
df.shape

(406829, 7)

In [18]:
df.duplicated().sum()

np.int64(5227)

In [19]:
df = df.drop_duplicates()

In [21]:
df.shape

(401602, 7)

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 401602 entries, 0 to 541908
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401602 non-null  object
 1   StockCode    401602 non-null  object
 2   Quantity     401602 non-null  int64
 3   InvoiceDate  401602 non-null  datetime64[us]
 4   UnitPrice    401602 non-null  float64
 5   CustomerID   401602 non-null  float64
 6   Country      401602 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(2), str(1)
memory usage: 24.5+ MB

In [23]:
df.nunique()

InvoiceNo      22190
StockCode       3684
Quantity         436
InvoiceDate    20460
UnitPrice        620
CustomerID      4372
Country           37
dtype: int64

In [24]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  401602.000000                      401602  401602.000000  401602.000000
mean       12.182579  2011-07-10 12:08:08.129840       3.474064   15281.172576
min    -80995.000000         2010-12-01 08:26:00       0.000000   12346.000000
25%         2.000000         2011-04-06 15:02:00       1.250000   13939.000000
50%         5.000000         2011-07-29 15:40:00       1.950000   15145.000000
75%        12.000000         2011-10-20 11:58:00       3.750000   16784.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       250.283248                         NaN      69.764209    1714.002257

In [25]:
df.head()

,InvoiceNo,StockCode,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [27]:
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

In [28]:
snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'nunique',
    'TotalAmount': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']

In [29]:
avg_order_value = df.groupby('CustomerID')['TotalAmount'].mean()

In [30]:
unique_products = df.groupby('CustomerID')['StockCode'].nunique()

In [31]:
total_qty = df.groupby('CustomerID')['Quantity'].sum()

In [32]:
customer_lifetime = df.groupby('CustomerID')['InvoiceDate'].agg(
    lambda x: (x.max() - x.min()).days
)

In [33]:
purchase_days = df.groupby('CustomerID')['InvoiceDate'].apply(
    lambda x: x.dt.date.nunique()
)

In [34]:
df.head()

,InvoiceNo,StockCode,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34